apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngtrigger-deployment-nginx
  labels:
    app: ngTriggerNginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngTriggerNginx
  template:
    metadata:
      labels:
        app: ngTriggerNginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
