name: todolist-cdng
replicas: 1
image: <+artifact.image>
dockercfg: <+artifact.imagePullSecret>

createNamespace: true
namespace: <+infrastructure.namespace>


env:
  config:
    key1: harnessDemo
  secrets:
    key2: thisSecret

